services:
  - type: web
    name: blumi-api
    env: python
    rootDir: ./
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.api:create_app --factory --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
