name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg fonts-dejavu-core fontconfig

      - name: Download fonts
        run: |
          mkdir -p backend/fonts
          # Download Orbitron, Montserrat, Poppins into backend/fonts
          curl -sL -o backend/fonts/Orbitron-Regular.ttf https://github.com/google/fonts/raw/main/ofl/orbitron/Orbitron-Regular.ttf || true
          curl -sL -o backend/fonts/Montserrat-Regular.ttf https://github.com/google/fonts/raw/main/ofl/montserrat/Montserrat-Regular.ttf || true
          curl -sL -o backend/fonts/Poppins-Regular.ttf https://github.com/google/fonts/raw/main/ofl/poppins/Poppins-Regular.ttf || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)
          export BLUMI_DUMP_FILTER=1
          pytest -q
